# Generated by Django 5.1.6 on 2025-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('last_location_seen', models.CharField(max_length=255)),
                ('last_date_time_seen', models.DateTimeField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing People',
                'db_table': 'MissingPersonsList',
            },
        ),
    ]
